server:
  port: 8888
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    username: root
    password: your password here
    url: jdbc:mysql://localhost:3306/fans?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    #druid配置
    #详见 https://blog.csdn.net/mulinsen77/article/details/87778601
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 8
    minIdle: 8
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

logging:
  file:
    name: ./src/main/resources/static/log/fans.log

fans:
  config:
    base-url: http://localhost:8888/
    upload-path: F:/graduation project/upload/
    redis-port: 127.0.0.1:6379